package com.eye.baidumapdemos.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.eye.baidumapdemos.dao.Route;
import com.eye.baidumapdemos.dao.Point;

import com.eye.baidumapdemos.dao.RouteDao;
import com.eye.baidumapdemos.dao.PointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig routeDaoConfig;
    private final DaoConfig pointDaoConfig;

    private final RouteDao routeDao;
    private final PointDao pointDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        routeDaoConfig = daoConfigMap.get(RouteDao.class).clone();
        routeDaoConfig.initIdentityScope(type);

        pointDaoConfig = daoConfigMap.get(PointDao.class).clone();
        pointDaoConfig.initIdentityScope(type);

        routeDao = new RouteDao(routeDaoConfig, this);
        pointDao = new PointDao(pointDaoConfig, this);

        registerDao(Route.class, routeDao);
        registerDao(Point.class, pointDao);
    }
    
    public void clear() {
        routeDaoConfig.getIdentityScope().clear();
        pointDaoConfig.getIdentityScope().clear();
    }

    public RouteDao getRouteDao() {
        return routeDao;
    }

    public PointDao getPointDao() {
        return pointDao;
    }

}
